<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AdminController:changer_etat' => function () {
    return ($this->privates['service_locator.48leRgN'] ?? $this->load(__DIR__.'/getServiceLocator_48leRgNService.php'));
}, 'App\\Controller\\RegistrationController:registerAction' => function () {
    return ($this->privates['service_locator.D6Mi.dK'] ?? $this->load(__DIR__.'/getServiceLocator_D6Mi_DKService.php'));
}, 'App\\Controller\\SecurityControllerPhpController:login' => function () {
    return ($this->privates['service_locator.3JDUr.I'] ?? $this->load(__DIR__.'/getServiceLocator_3JDUr_IService.php'));
}, 'App\\Controller\\UserController:changer_mdp' => function () {
    return ($this->privates['service_locator.u3qMPOI'] ?? $this->load(__DIR__.'/getServiceLocator_U3qMPOIService.php'));
}, 'App\\Controller\\AdminController::changer_etat' => function () {
    return ($this->privates['service_locator.48leRgN'] ?? $this->load(__DIR__.'/getServiceLocator_48leRgNService.php'));
}, 'App\\Controller\\RegistrationController::registerAction' => function () {
    return ($this->privates['service_locator.D6Mi.dK'] ?? $this->load(__DIR__.'/getServiceLocator_D6Mi_DKService.php'));
}, 'App\\Controller\\SecurityControllerPhpController::login' => function () {
    return ($this->privates['service_locator.3JDUr.I'] ?? $this->load(__DIR__.'/getServiceLocator_3JDUr_IService.php'));
}, 'App\\Controller\\UserController::changer_mdp' => function () {
    return ($this->privates['service_locator.u3qMPOI'] ?? $this->load(__DIR__.'/getServiceLocator_U3qMPOIService.php'));
})));
