<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.48leRgN' shared service.

return $this->privates['service_locator.48leRgN'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('mailer' => function () {
    return ($this->services['swiftmailer.mailer.default'] ?? $this->load(__DIR__.'/getSwiftmailer_Mailer_DefaultService.php'));
}));
